# **what?**
# Build release artifacts
#
# Expected build artifact layout:
#
# ├── dist
# │   ├── dbt-*.tar.gz
# │   ├── dbt-*.whl
# └── <release_notes>.md
#
#
# Inputs:
#  sha:                  The commit to attach to this release
#  version_number:       The release version number (i.e. 1.0.0b1, 1.2.3rc2, 1.0.0)
#  changelog_path:       Path to the changelog file for release notes
#  build_script_path:    Path to the build script
#  package_test_command: Command to use to check package runs
#  test_run:             Test run (Bucket to upload the artifact)
#  nightly_release:      Identifier that this is nightly release
#
# **why?**
# Reusable and consistent build process.
#
# **when?**
# Call after a successful version bump up.
# This workflow expects that the package version is bumped and the associated changelog living in sources.
#
# Validation Checks
#
#  1. Make sure the sha has a changelog entry for this version and the version bump has been completed.

name: Build

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      version_number:
        required: true
        type: string
      hatch_directory:
        required: false
        type: string
        default: "core"
      changelog_path:
        required: true
        type: string
      build_script_path:
        required: false # only required for legacy build path
        default: "scripts/build-dist.sh"
        type: string
      package_test_command:
        required: true
        default: "dbt --version"
        type: string
      test_run:
        required: false
        default: true
        type: boolean
      nightly_release:
        required: false
        default: false
        type: boolean
      use_hatch:
        required: false
        type: boolean
        description: "Use hatch for building packages"
        default: false # default to false for backwards compatibility

permissions:
  contents: write

env:
  ARTIFACT_RETENTION_DAYS: 2
  PYTHON_TARGET_VERSION: "3.10"
  NOTIFICATION_PREFIX: "[Build]"

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: "[DEBUG] Print Variables"
        run: |
          # WORKFLOW INPUTS
          echo The last commit sha in the release: ${{ inputs.sha }}
          echo The release version number:         ${{ inputs.version_number }}
          echo The hatch directory:                ${{ inputs.hatch_directory }}
          echo The changelog path:                 ${{ inputs.changelog_path }}
          echo The build script path:              ${{ inputs.build_script_path }}
          echo Use hatch:                          ${{ inputs.use_hatch }}
          echo The package test command:           ${{ inputs.package_test_command }}
          echo Test run:                           ${{ inputs.test_run }}
          echo Nightly release:                    ${{ inputs.nightly_release }}
          # ENVIRONMENT VARIABLES
          echo GitHub artifact retention days:     ${{ env.ARTIFACT_RETENTION_DAYS }}
          echo Python target version:              ${{ env.PYTHON_TARGET_VERSION }}
          echo Notification prefix:                ${{ env.NOTIFICATION_PREFIX }}

  audit-version-changelog:
    # Make sure the changelog has been generated and the version is up to date
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout ${{ github.repository }} Commit ${{ inputs.sha }}"
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}

      - name: "Audit Version And Parse Into Parts"
        id: semver
        uses: dbt-labs/actions/parse-semver@v1.1.0
        with:
          version: ${{ inputs.version_number }}

      - name: "Audit Changelog Exists"
        run: |
          title="Audit Changelog Exists"
          if test -f ${{ inputs.changelog_path }}
          then
            message="Specified file ${{ inputs.changelog_path }} - exists."
            echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
          else
            message="Specified file ${{ inputs.changelog_path }} does not exist! The changelog for this release must exist before running this workflow."
            git status
            echo "::error title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
            exit 1
          fi

      - name: "Check Current Version In Code"
        if: inputs.use_hatch == false
        run: |
          title="Check Current Version In Code"
          if grep -Fxq "current_version = ${{ inputs.version_number }}" .bumpversion.cfg
          then
            message="Version set to ${{ inputs.version_number }}."
            echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
          else
            message="Version not set to ${{ inputs.version_number }}. The version bump workflow must be complete before running this workflow."
            git status
            echo "::error title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
            exit 1
          fi

      - name: "Install Hatch"
        if: inputs.use_hatch == true
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install hatch

      - name: "Check Current Version In Code [hatch]"
        if: inputs.use_hatch == true
        working-directory: ${{ inputs.hatch_directory }}
        run: |
          title="Check Current Version In Code [hatch]"
          current_version=$(hatch version)
          echo "Current version: $current_version"
          if [ "$current_version" = "${{ inputs.version_number }}" ]
          then
            message="Version set to ${{ inputs.version_number }}."
            echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
          else
            message="Version not set to ${{ inputs.version_number }}. Current version is $current_version. The version bump workflow must be complete before running this workflow."
            git status
            echo "::error title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
            exit 1
          fi

  build-packages-legacy:
    if: inputs.use_hatch == false
    needs: [audit-version-changelog]
    uses: ./.github/workflows/build-legacy.yml
    with:
      sha: ${{ inputs.sha }}
      version_number: ${{ inputs.version_number }}
      changelog_path: ${{ inputs.changelog_path }}
      build_script_path: ${{ inputs.build_script_path }}

  build-packages-hatch:
    if: inputs.use_hatch == true
    needs: [audit-version-changelog]
    uses: ./.github/workflows/build-hatch.yml
    with:
      sha: ${{ inputs.sha }}
      version_number: ${{ inputs.version_number }}
      changelog_path: ${{ inputs.changelog_path }}
      hatch_directory: ${{ inputs.hatch_directory }}

  test-build:
    runs-on: ubuntu-latest
    needs: [build-packages-legacy, build-packages-hatch]
    if: always() && (needs.build-packages-legacy.result == success() || needs.build-packages-hatch.result == success())

    steps:
      - name: "Set up Python - ${{ env.PYTHON_TARGET_VERSION }}"
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_TARGET_VERSION }}

      - name: "Install Python Dependencies"
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --upgrade wheel
          python -m pip --version

      - name: "Download Build Artifact - ${{ inputs.version_number }}"
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # actions/download-artifact@v4
        with:
          name: ${{ inputs.version_number }}
          path: .

      - name: "[DEBUG] Display Structure Of All Downloaded Files"
        run: ls -R

      - name: "[DEBUG] Show Distributions"
        run: ls -lh dist/

      - name: "Install Wheel Distributions"
        run: |
          find ./dist/*.whl -maxdepth 1 -type f | xargs python -m pip install --force-reinstall --find-links=dist/

      - name: "[DEBUG] Check Wheel Distributions"
        run: |
          ${{ inputs.package_test_command }}

      - name: "Install Source Distributions"
        run: |
          find ./dist/*.gz -maxdepth 1 -type f | xargs python -m pip install --force-reinstall --find-links=dist/

      - name: "[DEBUG] Check Source Distributions"
        run: |
          ${{ inputs.package_test_command }}
