# **what?**
# Handle version bumping and testing using bumpversion/tox tooling.

# **why?**
# Reusable workflow for repositories using bumpversion for version management.

# **when?**
# Called by release-prep.yml workflow.

name: Version Management - Bumpversion

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      version_number:
        required: true
        type: string
      env_setup_script_path:
        required: false
        type: string
        default: ""
      changelog_exists:
        required: true
        type: string
      needs_version_update:
        required: true
        type: string
      changelog_path:
        required: true
        type: string
      base_version:
        required: true
        type: string
      prerelease:
        required: true
        type: string
      is_prerelease:
        required: true
        type: string
    secrets:
      IT_TEAM_MEMBERSHIP:
        description: "Token that can view org level teams"
        required: true

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  PYTHON_TARGET_VERSION: "3.10"
  NOTIFICATION_PREFIX: "[Release Preparation]"

jobs:
  generate-changelog-bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout ${{ github.repository }} Branch ${{ inputs.branch_name }}"
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: "Add Homebrew To PATH"
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: "Install Homebrew Packages"
        run: |
          brew install pre-commit
          brew tap miniscruff/changie https://github.com/miniscruff/changie
          brew install changie

      - name: "Set json File Name"
        id: json_file
        run: |
          echo "name=output_$GITHUB_RUN_ID.json" >> $GITHUB_OUTPUT

      - name: "Get Core Team Membership"
        run: |
          gh api -H "Accept: application/vnd.github+json" orgs/dbt-labs/teams/core-group/members > ${{ steps.json_file.outputs.name }}
        env:
          GH_TOKEN: ${{ secrets.IT_TEAM_MEMBERSHIP }}

      - name: "Set Core Team Membership for Changie Contributors exclusion"
        id: set_team_membership
        run: |
          team_list=$(jq -r '.[].login' ${{ steps.json_file.outputs.name }})
          echo $team_list
          team_list_single=$(echo $team_list | tr '\n' ' ')
          echo "CHANGIE_CORE_TEAM=$team_list_single" >> $GITHUB_ENV

      - name: "Delete the json File"
        run: |
          rm ${{ steps.json_file.outputs.name }}

      - name: "Generate Release Changelog"
        if: inputs.changelog_exists == 'false'
        run: |
          if [[ ${{ inputs.is_prerelease }} -eq 1 ]]
          then
          changie batch ${{ inputs.base_version }} --move-dir '${{ inputs.base_version }}' --prerelease ${{ inputs.prerelease }}
          elif [[ -d ".changes/${{ inputs.base_version }}" ]]
          then
          changie batch ${{ inputs.base_version }} --include '${{ inputs.base_version }}' --remove-prereleases
          else # releasing a final patch with no prereleases
          changie batch ${{ inputs.base_version }}
          fi
          changie merge
          git status

      - name: "Check Changelog Created Successfully"
        if: inputs.changelog_exists == 'false'
        run: |
          title="Changelog"
          if [[ -f ${{ inputs.changelog_path }} ]]
          then
          message="Changelog file created successfully"
          echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
          else
          message="Changelog failed to generate"
          echo "::error title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"
          exit 1
          fi

      - name: "Set up Python - ${{ env.PYTHON_TARGET_VERSION }}"
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_TARGET_VERSION }}

      - name: "Install Python Dependencies"
        if: inputs.needs_version_update == 'true'
        run: |
          python3 -m venv env
          source env/bin/activate
          python -m pip install --upgrade pip

      - name: "Bump Version To ${{ inputs.version_number }}"
        if: inputs.needs_version_update == 'true'
        run: |
          source env/bin/activate
          if [ -f "editable-requirements.txt" ]
          then
          python -m pip install -r dev-requirements.txt -r editable-requirements.txt
          else
          python -m pip install -r dev-requirements.txt
          fi
          env/bin/bumpversion --allow-dirty --new-version ${{ inputs.version_number }} major
          git status

      - name: "[Notification] Bump Version To ${{ inputs.version_number }}"
        if: inputs.needs_version_update == 'true'
        run: |
          title="Version bump"
          message="Version successfully bumped in codebase to ${{ inputs.version_number }}"
          echo "::notice title=${{ env.NOTIFICATION_PREFIX }}: $title::$message"

      - name: "Remove Trailing Whitespace Via Pre-commit"
        run: |
          pre-commit run trailing-whitespace --files .bumpversion.cfg CHANGELOG.md .changes/* || true
          git status

      - name: "Removing Extra Newlines Via Pre-commit"
        run: |
          pre-commit run end-of-file-fixer --files .bumpversion.cfg CHANGELOG.md .changes/* || true
          git status

      - name: "Commit & Push Changes"
        run: |
          #Data for commit
          user="Github Build Bot"
          email="buildbot@fishtownanalytics.com"
          commit_message="Bumping version to ${{ inputs.version_number }} and generate changelog"
          #Commit changes to branch
          git config user.name "$user"
          git config user.email "$email"
          git pull
          git add .
          git commit -m "$commit_message"
          git push

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: [generate-changelog-bump-version]

    env:
      TOXENV: unit

    steps:
      - name: "Checkout ${{ github.repository }} Branch ${{ inputs.branch_name }}"
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: "Set up Python - ${{ env.PYTHON_TARGET_VERSION }}"
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_TARGET_VERSION }}

      - name: "Install Python Dependencies"
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install tox
          python -m pip --version
          python -m tox --version

      - name: "Run Tox"
        run: tox

  run-integration-tests:
    runs-on: ubuntu-24.04
    needs: [generate-changelog-bump-version]
    if: inputs.env_setup_script_path != ''

    env:
      TOXENV: integration

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: "Checkout ${{ github.repository }} Branch ${{ inputs.branch_name }}"
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: "Setup Environment Variables - ./${{ inputs.env_setup_script_path }}"
        run: source ./${{ inputs.env_setup_script_path }}

      - name: "Setup Environment Variables - Secrets Context"
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # actions/github-script@v7
        id: check-env
        with:
          result-encoding: string
          script: |
            try {
              const { SECRETS_CONTEXT, INTEGRATION_TESTS_SECRETS_PREFIX } = process.env
              const secrets = JSON.parse(SECRETS_CONTEXT)

              if (INTEGRATION_TESTS_SECRETS_PREFIX) {
              for (const [key, value] of Object.entries(secrets)) {
                if (key.startsWith(INTEGRATION_TESTS_SECRETS_PREFIX)) {
                  core.exportVariable(key, value)
                }
              }
              } else {
              core.info("The INTEGRATION_TESTS_SECRETS_PREFIX env variable is empty or not defined, skipping the secrets setup.")
              }
            } catch (err) {
              core.error("Error while reading or parsing the JSON")
              core.setFailed(err)
            }
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: "Set up Python - ${{ env.PYTHON_TARGET_VERSION }}"
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_TARGET_VERSION }}

      - name: "Set Up Postgres (dbt-core)"
        if: ${{ contains(github.repository, 'dbt-labs/dbt-core') }}
        run: |
          ./test/setup_db.sh
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGPASSWORD: password

      - name: "Install python tools"
        run: |
          python -m pip install --user --upgrade pip
          python -m pip --version
          python -m pip install tox
          tox --version

      - name: "Run tests"
        run: tox
